<?xml version="1.0" encoding="utf-8"?><Database Name="UsersDB" Class="LINQtoSQLdbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=BLACKLAMBO0E70\SQLEXPRESS;Initial Catalog=UsersDB;Integrated Security=True" SettingsObjectName="MMA.Properties.Settings" SettingsPropertyName="UsersDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UsersTable" Member="UsersTable">
    <Type Name="UsersTable">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="surname" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="patronymic" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="initials" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="position" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>